# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0003_author_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='books_authors.Book'),
        ),
    ]
