# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books', '0004_user_uploaded_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_books',
            field=models.ManyToManyField(related_name='liked_users', to='likes_books.Book'),
        ),
    ]
