# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review', '0002_auto_20170924_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='comment',
        ),
    ]
